# Generated by Django 5.1.3 on 2025-07-03 17:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the song.', primary_key=True, serialize=False)),
                ('audio_file', models.FileField(blank=True, help_text='The audio file of the song.', null=True, upload_to='songs/')),
                ('artist', models.CharField(help_text='The artist of the song.', max_length=255)),
                ('thumbnail', models.ImageField(blank=True, help_text='The thumbnail image of the song.', null=True, upload_to='thumbnails/')),
                ('vinyl_thumbnail', models.ImageField(blank=True, help_text='The vinyl thumbnail image of the song.', null=True, upload_to='vinyl_thumbnails/')),
                ('title', models.CharField(help_text='The primary title of the song.', max_length=255)),
                ('alternate_titles', models.JSONField(blank=True, default=list, help_text='Array of alternative titles, common misspellings, or working titles.', null=True)),
                ('version_subtitle', models.CharField(blank=True, help_text="e.g., 'Instrumental,' 'Acoustic Mix,' 'Radio Edit,' 'Remix feat. [Artist]'.", max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='A brief overview or detailed description of the song.', null=True)),
                ('release_date', models.DateField(blank=True, help_text='The date the song was first commercially released.', null=True)),
                ('creation_date', models.DateField(blank=True, help_text='The date the song was composed/first created.', null=True)),
                ('language', models.CharField(default='en', help_text="The primary language of the lyrics (if any), e.g., 'en', 'es'.", max_length=10)),
                ('explicit_content', models.BooleanField(default=False, help_text='Flag indicating if the song contains explicit lyrics or themes.')),
                ('tempo_bpm', models.IntegerField(blank=True, help_text='Beats Per Minute (BPM) of the song.', null=True)),
                ('key', models.CharField(blank=True, help_text="Musical key of the song (e.g., 'C Major', 'A Minor', 'F#m').", max_length=50, null=True)),
                ('time_signature', models.CharField(blank=True, help_text="Time signature of the song (e.g., '4/4', '3/4').", max_length=10, null=True)),
                ('duration_seconds', models.IntegerField(help_text='Total duration of the song in seconds.')),
                ('genres', models.JSONField(default=list, help_text="Array of primary and secondary genres (e.g., ['Hip-Hop', 'Trap']).")),
                ('moods', models.JSONField(blank=True, default=list, help_text="Array of moods or emotions evoked (e.g., ['Uplifting', 'Melancholy']).", null=True)),
                ('keywords_tags', models.JSONField(blank=True, default=list, help_text="Additional keywords for search and categorization (e.g., ['summer', 'driving']).", null=True)),
                ('instruments', models.JSONField(blank=True, default=list, help_text="List of prominent instruments in the track (e.g., ['piano', 'drums']).", null=True)),
                ('vocal_description', models.CharField(blank=True, help_text="Describes the vocal presence (e.g., 'Male Lead', 'No Vocals').", max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
