# Generated by Django 5.1.3 on 2025-07-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_track_delete_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(blank=True, help_text='The audio file of the song.', max_length=255, null=True, upload_to='tracks/'),
        ),
    ]
