# Generated by Django 5.1.3 on 2025-07-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_track_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(blank=True, help_text='The audio file of the song.', max_length=255, upload_to='tracks/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration_seconds',
            field=models.IntegerField(help_text='Total duration of the song in seconds.', null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='genres',
            field=models.JSONField(default=list, help_text="Array of primary and secondary genres (e.g., ['Hip-Hop', 'Trap']).", null=True),
        ),
    ]
