# Generated by Django 5.1.3 on 2025-07-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_track_audio_file_alter_track_duration_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(blank=True, help_text='The audio file of the song.', max_length=255, null=True, upload_to='tracks/'),
        ),
    ]
